id: I987D26BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:52:45+00:00'
last_modified: '2022-06-07T16:40:22.738406+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7505
  title: ཀློང་ཆེན་རབ་འབྱམས་པའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7B65:
      image_group_id: I1KG2058
      title: ''
      total_pages: 66
      order: 1
      base_file: 7B65.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
